[project]
name = "linkedin-post-via-openai-api"
version = "0.1.0"
description = "This is LinkedIn post generator via OpenAI APIs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
